/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (controllerName=='home') return true
                if (controllerName=='door') return true
                if (controllerName=='public') return true
                if (controllerName=='jasper') return true
                if (controllerName=='admin') return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
